<?php

/** @var \GlobalLogic\Blog\Block\Post\ListPost $block */

$posts = $this->getPostList();
?>

<div class="template">
    <?php foreach ($posts as $post) : ?>
        <h2>
            <?= $post->getName() ?>
        </h2>
        <p>
            <?= $post->getShortDescription() ?>
        </p>
        <a href="
        <?= $block->escapeUrl($post->getPostUrl()) ?>">
            <?= __('Read More...') ?>
        </a>
    <?php endforeach; ?>
</div>